name: Trigger auto deployment for leave-agent-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'api_func/**'
    - 'utils/**'
    - 'pyproject.toml'
    - 'uv.lock'
    - '.github/workflows/leave-agent-api-AutoDeployTrigger-8a6afbd2-9504-42c5-beec-82efad032cc0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Docker login to ACR
        run: |
          echo "${{ secrets.LEAVEAGENTAPI_REGISTRY_PASSWORD }}" | docker login ${{ secrets.LEAVEAGENTAPI_REGISTRY_URL }} \
            --username "${{ secrets.LEAVEAGENTAPI_REGISTRY_USERNAME }}" \
            --password-stdin

      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.LEAVEAGENTAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LEAVEAGENTAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LEAVEAGENTAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: api_func/Dockerfile
          acrName: ${{ secrets.LEAVEAGENTAPI_ACR_NAME }}
          acrUsername: ${{ secrets.LEAVEAGENTAPI_REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.LEAVEAGENTAPI_REGISTRY_PASSWORD }}
          containerAppName: leave-agent-api
          resourceGroup: presobh-group
          imageToBuild: ${{ secrets.LEAVEAGENTAPI_REGISTRY_URL }}/leave-agent-api:${{ github.sha }}


