name: Trigger auto deployment for leave-mcp-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'mcp_func/**'
    - 'utils/**'
    - 'pyproject.toml'
    - 'uv.lock'
    - '.github/workflows/leave-mcp-api-AutoDeployTrigger-ef216533-6c53-417d-b122-03763d2732f4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.LEAVEMCPAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LEAVEMCPAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LEAVEMCPAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: ${{ secrets.LEAVEAGENTAPI_REGISTRY_URL }} 
          registryUsername: ${{ secrets.LEAVEMCPAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LEAVEMCPAPI_REGISTRY_PASSWORD }}
          containerAppName: leave-mcp-api
          resourceGroup: presobh-group
          imageToBuild: ${{ secrets.LEAVEAGENTAPI_REGISTRY_URL }}/leave-mcp-api:${{ github.sha }}


